### ISSUE TITLE
Chrome APP is hard to reset to a zero state.

### ISSUE THREAD

**Issue by karman-san** [limpkin/mooltipass#154]
I found several scenarios in wich app hangs and stops working properly when running test. 

The only way to make it work again is to reset the app by disabling it and reenabling it again in chrome extensions menu, making it hard to reset if someone doesn't know it.

**Comment by kasbah** [comment]
Thanks karman-san, the issue is more that there shouldn't be a need reset the app. If you running tests then enable the dev mode in chrome and you can right click on the app an reload it that way. 

Please report issues where the app reset is required though (it should never be required in normal use).

**Comment by limpkin** [comment]
There wouldn't be a need to reset the app if said app was made correctly. In the mean time, there should be an easier way for beta testers (and unlucky future users) to easily reset the app.

**Comment by kasbah** [comment]
There is: enable the dev mode on chrome.
