### ISSUE TITLE
Multipass 'types' too fast for android?

### ISSUE THREAD

**Issue by firstnevyn** [limpkin/mooltipass#163]
When attempting to use my mooltipass to enter credentials on my android tablet (Samsung Galaxy Tab A)

The credentials are shorter than anticipated. and if I display them I see there are dropped characters.

however everything is fine on my linux pc.

Grant

**Comment by limpkin** [comment]
Hello Grant!

Are you located in the US?

Regards

**Comment by firstnevyn** [comment]
No.. Melbourne Australia.

Grant.

**Comment by limpkin** [comment]
Did you correctly set the correct keyboard layout inside the mooltipass settings tab?
Sometimes you need to set EN_US for tablets.

Regards

**Comment by henryk** [comment]
Can we make the typing speed configurable (preferably per login, or smartly: see below)? My situation: I have to administer some things through a Citrix ICA connection. And instead of having to copy-paste credentials from my local password manager as I'm doing now, I'd like to mooltipass them in (keyboard emulation, yeah!).

Problem: Repeated characters get dropped. Instead of login name "root" the other side sees "rot". I'm guessing the ICA applies some sort of debounce or is generally too slow. This is not a problem when manually typing, but makes mooltipass unusable, as I'm also having a repeated character in the password. So for the ICA case at least character repetition probably needs to be slower.

**Comment by rrix** [comment]
I am having this issue on a Samsung Tab S2 with a few different OTG cables and in many apps; it seems like it may just be typing too quickly. I did not have this issue on the LG G-Pad II, which has a dedicated USB port, so I think it may be some sort of translation issue with the Android OS, but I'm about to just work around this by putting sleeps in to the Mooltipass firmware... Having a configuration for this would be very nice.

**Comment by limpkin** [comment]
Hello rrix,

We'll therefore implement it in our next firmware version.
