### ISSUE TITLE
Chrome+extension+stackoverflow.com not setting credentials

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#379]
### Expected behavior
Entering login credentials to stackoverflow.com generates a credential update request with username and password

### Actual behavior
Credential request sent to MP is blank.

### Step by step guide to reproduce the problem
Clear our any credentials for stackoverflow.com and attempt to sign in, see that credential update requests gives blank username.  I've seen this on some other websites, but this was the first time I noticed it that I figured it should be reported rather than just worked around by manually entering in management mode.

Many other websites tested and worked with this input without issues.

### Mooltipass version
Which Mooltipass do you use? MPmini (homemade from git resources)
What is its firmware version? 1.2 (stock POST_KICKSTARTER_SETUP with some additional #defines to remove features)

**Comment by limpkin** [comment]
Hello,

I'm guessing you managed to build your minis! Congratulations!
I've just pushed an extension update (.75) could you let me know if the bug
still persists?

Thanks

On Apr 11, 2017 11:58 PM, "kbembedded" <notifications@github.com> wrote:

Expected behavior

Entering login credentials to stackoverflow.com generates a credential
update request with username and password
Actual behavior

Credential request sent to MP is blank.
Step by step guide to reproduce the problem

Clear our any credentials for stackoverflow.com and attempt to sign in, see
that credential update requests gives blank username. I've seen this on
some other websites, but this was the first time I noticed it that I
figured it should be reported rather than just worked around by manually
entering in management mode.

Many other websites tested and worked with this input without issues.
Mooltipass version

Which Mooltipass do you use? MPmini (homemade from git resources)
What is its firmware version? 1.2 (stock POST_KICKSTARTER_SETUP with some
additional #defines to remove features)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/limpkin/mooltipass/issues/379>, or mute the thread

**Comment by kbembedded** [comment]
I have.  Though I am still doing some tinkering to create instructions for bootstrapping a single device reliably.

.75 of the extension appears to no longer have this issue.  Thanks.

**Comment by limpkin** [comment]
thanks a lot for your time :)
