### ISSUE TITLE
Generated-password field not working 100%

### ISSUE THREAD

**Issue by limpkin** [limpkin/mooltipass#387]
from a reddit thread: 

When you click on the key symbol to generate a new password and change the password a bit (typing a character or two, and deleting others), then the "copy to all password fields" copies the originally generated password and not the modified password.
I'd much prefer it to copy the modified password, or failing that disable editing in the field so that it is display-only.
Windows app "Credential Storage".

**Comment by nelabidi** [comment]
I am able to reproduce the issue, I found what it copies the old password instead of the modified one, I am working on the solution

**Comment by nelabidi** [comment]
This issue can be reproduced this way:
 - click on the password icon, 
 - click somewhere else to close it, 
 - click again to show the dialog and try to modify the generated password
 - click on "copy to all password fileds" it will copy the original one
 
the cause is multiple creation of password generator dialog created multiple fields with css ".mooltipass-password-generator", the "mpJQ(".mooltipass-password-generator").val();"  will return the value of the first element with class ".mooltipass-password-generator"

**Comment by limpkin** [comment]
Thanks a lot for your contribution!
