### ISSUE TITLE
Cannot backup old Mooltipass

### ISSUE THREAD

**Issue by NicoHood** [limpkin/mooltipass#406]
With the current chroma app 2.0.78 I cannot do a memory export. It requests to enter MMM and then the app aborts with an USB error. It was functional with my old 2.0.51 legacy version which I have as my personal fallback.

**Comment by limpkin** [comment]
" All issues not following a template will be directly closed."

**Comment by NicoHood** [comment]
"All issues not following a template or your general pleasures are not existent or features."

**Comment by limpkin** [comment]
You have been here since the beginning of the mooltipass mini development, have participated in all the discussions and are therefore more than familiar with our development and issue reporting practices.  
You are familiar with the code, created pull requests yet you prefer not following rules that you are fully aware of and that are explicitly mentioned when you clicked that "new issue" button.

**Comment by NicoHood** [comment]
I was always against this issue handling. And I am not familiar with any javascript code, nor the programming language itself. Other projects are glad if people test their shit.
